<?php
require_once('functions.php');
print_header();
echo <<<HERE
<div class="container" style="margin-top:75px!important">
<h1 class="text-center">What is this thing?</h1>
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
		
			<h4 class="text-center">The basic idea</h4>
		
			<p class="help-block" style="text-indent:15px">
				This is basically a live-action Sphinx configuration tutorial. It's not that configuring Sphinx
				is particularly difficult, it's just that Sphinx is pretty awesome (pretty flexible)-- there are a lot of options. All the options
				could overwhelm newcomers. So, to help create a painless experience for those just getting started, I've started to bring all these options,
				and some explanation, into these forms.</p>
			
			<p class="help-block">	
				So... <ul><li><p class="help-block">point</p></li><li><p class="help-block">click</p></li><li><p class="help-block">type</p></li><li><p class="help-block">copy and paste the config generated by these forms</p></li>
				<li><p class="help-block">run indexer</p></li><li><p class="help-block">start searchd</p></li></ul><p class="help-block">...and you're ready to start Sphinx searching.</p>
			<br />
			<h4 class="text-center">Questions?</h4>
		
			<p class="help-block" style="text-indent:15px">
				Email me at steve at sphinxsearch dot com. Or, want to see some of the 
				other things I'm exploring (mostly related to Sphinx as well)?
				Go read my <a href="http://sphinxish.blogspot.com">personal blog</a>. Want Sphinx news and some 
				tutorials? Go to the <a href="http://sphinxsearch.com/blog">fulltext diary</a>.
			</p>
		</div>
	</div>
</div>
HERE;
?>
